#############################################################################
# Makefile for building: qtTrainingPlan
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon May 31 07:25:13 2010
# Project:  qtTrainingPlan.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtTrainingPlan.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtWebKit -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		ctraining.cpp \
		common.cpp \
		ctime.cpp \
		cclientdata.cpp \
		cedittraining.cpp \
		ceditday.cpp \
		ceditsession.cpp \
		cedittask.cpp \
		cedittasks.cpp \
		cexportpdf.cpp \
		ceditsport.cpp \
		cedithr.cpp moc_mainwindow.cpp \
		moc_cedittraining.cpp \
		moc_ceditday.cpp \
		moc_ceditsession.cpp \
		moc_cedittask.cpp \
		moc_cedittasks.cpp \
		moc_cexportpdf.cpp \
		moc_ceditsport.cpp \
		moc_cedithr.cpp
OBJECTS       = main.o \
		mainwindow.o \
		ctraining.o \
		common.o \
		ctime.o \
		cclientdata.o \
		cedittraining.o \
		ceditday.o \
		ceditsession.o \
		cedittask.o \
		cedittasks.o \
		cexportpdf.o \
		ceditsport.o \
		cedithr.o \
		moc_mainwindow.o \
		moc_cedittraining.o \
		moc_ceditday.o \
		moc_ceditsession.o \
		moc_cedittask.o \
		moc_cedittasks.o \
		moc_cexportpdf.o \
		moc_ceditsport.o \
		moc_cedithr.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtTrainingPlan.pro
QMAKE_TARGET  = qtTrainingPlan
DESTDIR       = 
TARGET        = qtTrainingPlan

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_cedittraining.h ui_ceditday.h ui_ceditsession.h ui_cedittask.h ui_cedittasks.h ui_cexportpdf.h ui_ceditsport.h ui_cedithr.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtTrainingPlan.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtTrainingPlan.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtTrainingPlan.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtTrainingPlan1.0.0 || $(MKDIR) .tmp/qtTrainingPlan1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtTrainingPlan1.0.0/ && $(COPY_FILE) --parents mainwindow.h ctraining.h common.h ctime.h cclientdata.h cedittraining.h ceditday.h ceditsession.h cedittask.h cedittasks.h cexportpdf.h ceditsport.h cedithr.h .tmp/qtTrainingPlan1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp ctraining.cpp common.cpp ctime.cpp cclientdata.cpp cedittraining.cpp ceditday.cpp ceditsession.cpp cedittask.cpp cedittasks.cpp cexportpdf.cpp ceditsport.cpp cedithr.cpp .tmp/qtTrainingPlan1.0.0/ && $(COPY_FILE) --parents mainwindow.ui cedittraining.ui ceditday.ui ceditsession.ui cedittask.ui cedittasks.ui cexportpdf.ui ceditsport.ui cedithr.ui .tmp/qtTrainingPlan1.0.0/ && $(COPY_FILE) --parents qtTrainingPlan_de_AT.ts qtTrainingPlan_de_DE.ts .tmp/qtTrainingPlan1.0.0/ && (cd `dirname .tmp/qtTrainingPlan1.0.0` && $(TAR) qtTrainingPlan1.0.0.tar qtTrainingPlan1.0.0 && $(COMPRESS) qtTrainingPlan1.0.0.tar) && $(MOVE) `dirname .tmp/qtTrainingPlan1.0.0`/qtTrainingPlan1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtTrainingPlan1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_cedittraining.cpp moc_ceditday.cpp moc_ceditsession.cpp moc_cedittask.cpp moc_cedittasks.cpp moc_cexportpdf.cpp moc_ceditsport.cpp moc_cedithr.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_cedittraining.cpp moc_ceditday.cpp moc_ceditsession.cpp moc_cedittask.cpp moc_cedittasks.cpp moc_cexportpdf.cpp moc_ceditsport.cpp moc_cedithr.cpp
moc_mainwindow.cpp: cclientdata.h \
		ctime.h \
		common.h \
		ctraining.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_cedittraining.cpp: cedittraining.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cedittraining.h -o moc_cedittraining.cpp

moc_ceditday.cpp: ceditday.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ceditday.h -o moc_ceditday.cpp

moc_ceditsession.cpp: ceditsession.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ceditsession.h -o moc_ceditsession.cpp

moc_cedittask.cpp: ctime.h \
		common.h \
		cedittask.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cedittask.h -o moc_cedittask.cpp

moc_cedittasks.cpp: ctime.h \
		common.h \
		cedittasks.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cedittasks.h -o moc_cedittasks.cpp

moc_cexportpdf.cpp: cexportpdf.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cexportpdf.h -o moc_cexportpdf.cpp

moc_ceditsport.cpp: ceditsport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ceditsport.h -o moc_ceditsport.cpp

moc_cedithr.cpp: cedithr.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cedithr.h -o moc_cedithr.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_cedittraining.h ui_ceditday.h ui_ceditsession.h ui_cedittask.h ui_cedittasks.h ui_cexportpdf.h ui_ceditsport.h ui_cedithr.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_cedittraining.h ui_ceditday.h ui_ceditsession.h ui_cedittask.h ui_cedittasks.h ui_cexportpdf.h ui_ceditsport.h ui_cedithr.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_cedittraining.h: cedittraining.ui
	/usr/bin/uic-qt4 cedittraining.ui -o ui_cedittraining.h

ui_ceditday.h: ceditday.ui
	/usr/bin/uic-qt4 ceditday.ui -o ui_ceditday.h

ui_ceditsession.h: ceditsession.ui
	/usr/bin/uic-qt4 ceditsession.ui -o ui_ceditsession.h

ui_cedittask.h: cedittask.ui
	/usr/bin/uic-qt4 cedittask.ui -o ui_cedittask.h

ui_cedittasks.h: cedittasks.ui
	/usr/bin/uic-qt4 cedittasks.ui -o ui_cedittasks.h

ui_cexportpdf.h: cexportpdf.ui
	/usr/bin/uic-qt4 cexportpdf.ui -o ui_cexportpdf.h

ui_ceditsport.h: ceditsport.ui
	/usr/bin/uic-qt4 ceditsport.ui -o ui_ceditsport.h

ui_cedithr.h: cedithr.ui
	/usr/bin/uic-qt4 cedithr.ui -o ui_cedithr.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		cclientdata.h \
		ctime.h \
		common.h \
		ctraining.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		cclientdata.h \
		ctime.h \
		common.h \
		ctraining.h \
		ui_mainwindow.h \
		ceditsport.h \
		cedittraining.h \
		ceditday.h \
		ceditsession.h \
		cedittask.h \
		cedittasks.h \
		cexportpdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

ctraining.o: ctraining.cpp ctraining.h \
		common.h \
		ctime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ctraining.o ctraining.cpp

common.o: common.cpp common.h \
		ctime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o common.cpp

ctime.o: ctime.cpp ctime.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ctime.o ctime.cpp

cclientdata.o: cclientdata.cpp cclientdata.h \
		ctime.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cclientdata.o cclientdata.cpp

cedittraining.o: cedittraining.cpp cedittraining.h \
		ui_cedittraining.h \
		common.h \
		ctime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cedittraining.o cedittraining.cpp

ceditday.o: ceditday.cpp ceditday.h \
		ui_ceditday.h \
		common.h \
		ctime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ceditday.o ceditday.cpp

ceditsession.o: ceditsession.cpp ceditsession.h \
		ui_ceditsession.h \
		common.h \
		ctime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ceditsession.o ceditsession.cpp

cedittask.o: cedittask.cpp cedittask.h \
		ctime.h \
		common.h \
		ui_cedittask.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cedittask.o cedittask.cpp

cedittasks.o: cedittasks.cpp cedittasks.h \
		ctime.h \
		common.h \
		ui_cedittasks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cedittasks.o cedittasks.cpp

cexportpdf.o: cexportpdf.cpp cexportpdf.h \
		ui_cexportpdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cexportpdf.o cexportpdf.cpp

ceditsport.o: ceditsport.cpp ceditsport.h \
		ui_ceditsport.h \
		common.h \
		ctime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ceditsport.o ceditsport.cpp

cedithr.o: cedithr.cpp cedithr.h \
		ui_cedithr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cedithr.o cedithr.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_cedittraining.o: moc_cedittraining.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cedittraining.o moc_cedittraining.cpp

moc_ceditday.o: moc_ceditday.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ceditday.o moc_ceditday.cpp

moc_ceditsession.o: moc_ceditsession.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ceditsession.o moc_ceditsession.cpp

moc_cedittask.o: moc_cedittask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cedittask.o moc_cedittask.cpp

moc_cedittasks.o: moc_cedittasks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cedittasks.o moc_cedittasks.cpp

moc_cexportpdf.o: moc_cexportpdf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cexportpdf.o moc_cexportpdf.cpp

moc_ceditsport.o: moc_ceditsport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ceditsport.o moc_ceditsport.cpp

moc_cedithr.o: moc_cedithr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cedithr.o moc_cedithr.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

